# Generated by Django 6.0 on 2026-01-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('hindi', 'Hindi'), ('english', 'English'), ('marathi', 'Marathi'), ('telugu', 'Telugu'), ('kannada', 'Kannada'), ('malayalam', 'Malayalam')], max_length=50),
        ),
    ]
